#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0x1A541148054E9E38 (infra-root@openstack.org)
#
Name     : oslo.context
Version  : 2.22.0
Release  : 45
URL      : http://tarballs.openstack.org/oslo.context/oslo.context-2.22.0.tar.gz
Source0  : http://tarballs.openstack.org/oslo.context/oslo.context-2.22.0.tar.gz
Source99 : http://tarballs.openstack.org/oslo.context/oslo.context-2.22.0.tar.gz.asc
Summary  : Oslo Context library
Group    : Development/Tools
License  : Apache-2.0
Requires: oslo.context-license = %{version}-%{release}
Requires: oslo.context-python = %{version}-%{release}
Requires: oslo.context-python3 = %{version}-%{release}
Requires: debtcollector
Requires: pbr
BuildRequires : buildreq-distutils3
BuildRequires : pbr

%description
====================
Oslo Context Library
====================
The Oslo context library has helpers to maintain useful information
about a request context. The request context is usually populated in
the WSGI pipeline and used by various modules such as logging.

%package license
Summary: license components for the oslo.context package.
Group: Default

%description license
license components for the oslo.context package.


%package python
Summary: python components for the oslo.context package.
Group: Default
Requires: oslo.context-python3 = %{version}-%{release}

%description python
python components for the oslo.context package.


%package python3
Summary: python3 components for the oslo.context package.
Group: Default
Requires: python3-core

%description python3
python3 components for the oslo.context package.


%prep
%setup -q -n oslo.context-2.22.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1551029117
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/oslo.context
cp LICENSE %{buildroot}/usr/share/package-licenses/oslo.context/LICENSE
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/oslo.context/LICENSE

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
