#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0xD9631FEAF0CC6227 (infra-root@openstack.org)
#
Name     : oslo.context
Version  : 2.10.0
Release  : 36
URL      : http://tarballs.openstack.org/oslo.context/oslo.context-2.10.0.tar.gz
Source0  : http://tarballs.openstack.org/oslo.context/oslo.context-2.10.0.tar.gz
Source99 : http://tarballs.openstack.org/oslo.context/oslo.context-2.10.0.tar.gz.asc
Summary  : Oslo Context library
Group    : Development/Tools
License  : Apache-2.0
Requires: oslo.context-python
Requires: pbr
Requires: positional
BuildRequires : pbr
BuildRequires : pip
BuildRequires : python-dev
BuildRequires : python3-dev
BuildRequires : setuptools

%description
====================
Oslo Context Library
====================
.. image:: https://img.shields.io/pypi/v/oslo.context.svg
:target: https://pypi.python.org/pypi/oslo.context/
:alt: Latest Version

%package python
Summary: python components for the oslo.context package.
Group: Default

%description python
python components for the oslo.context package.


%prep
%setup -q -n oslo.context-2.10.0

%build
export LANG=C
export SOURCE_DATE_EPOCH=1489272834
python2 setup.py build -b py2
python3 setup.py build -b py3

%install
export SOURCE_DATE_EPOCH=1489272834
rm -rf %{buildroot}
python2 -tt setup.py build -b py2 install --root=%{buildroot} --force
python3 -tt setup.py build -b py3 install --root=%{buildroot} --force

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)
/usr/lib/python*/*
